name: BuffedItems
version: '${project.version}'
main: io.github.altkat.BuffedItems.BuffedItems
api-version: '1.21'
softdepend: [Nexo, ItemsAdder, PlaceholderAPI, Vault, CoinsEngine]
authors: [StreetMelodeez(AltKat)]
description: 'Create custom items with permanent potion effects and attributes. Fully configurable via /bi menu with advanced editor UI.'
commands:
  buffeditems:
    description: Main command for the BuffedItems plugin.
    usage: /<command> [give|reload|list|menu|upgrade|wiki|update|recipes|sets]
    aliases: [bi, buffitems]
permissions:
  buffeditems.admin:
    description: Grants access to all BuffedItems commands.
    children:
      buffeditems.command.give: true
      buffeditems.command.reload: true
      buffeditems.command.list: true
      buffeditems.command.menu: true
      buffeditems.command.upgrade: true
      buffeditems.command.wiki: true
      buffeditems.command.update: true
      buffeditems.command.recipes: true
      buffeditems.command.sets: true
  buffeditems.command.give:
    description: Allows usage of the /buffeditems give command.
    default: op
  buffeditems.command.reload:
    description: Allows usage of the /buffeditems reload command.
    default: op
  buffeditems.command.list:
    description: Allows usage of the /buffeditems list command.
    default: op
  buffeditems.command.menu:
    description: Allows opening the BuffedItems GUI menu.
    default: op
  buffeditems.command.wiki:
    description: Allows usage of the /buffeditems wiki command.
    default: op
  buffeditems.command.update:
    description: Allows usage of the /buffeditems update command.
    default: op
  buffeditems.command.upgrade:
    description: Allows usage of the /buffeditems upgrade command.
    default: true
  buffeditems.command.recipes:
    description: Allows viewing the public crafting recipes menu.
    default: true
  buffeditems.command.sets:
    description: Allows viewing the item sets menu.
    default: true