name: BuffedItems
version: '${project.version}'
main: io.github.altkat.BuffedItems.BuffedItems
api-version: '1.16'
softdepend: [Nexo, ItemsAdder, PlaceholderAPI]
authors: [StreetMelodeez(AltKat)]
description: Create custom items with permanent potion effects and attributes.
commands:
  buffeditems:
    description: Main command for the BuffedItems plugin.
    usage: /<command> [give|reload|list]
    aliases: [bi, buffitems]
permissions:
  buffeditems.admin:
    description: Grants access to all BuffedItems commands.
    children:
      - buffeditems.command.give
      - buffeditems.command.reload
      - buffeditems.command.list
      - buffeditems.command.menu
  buffeditems.command.give:
    description: Allows usage of the /buffeditems give command.
    default: op
  buffeditems.command.reload:
    description: Allows usage of the /buffeditems reload command.
    default: op
  buffeditems.command.list:
    description: Allows usage of the /buffeditems list command.
    default: op
  buffeditems.command.menu:
    description: Allows opening the BuffedItems GUI menu.
    default: op